// <auto-generated />
using CodeFirstDBFirst.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstDBFirst.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20230216094953_AggiuntoCampo1")]
    partial class AggiuntoCampo1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstDBFirst.DB.Tabella1", b =>
                {
                    b.Property<int>("Pk")
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    b.Property<string>("Campo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descr")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("DESCR")
                        .IsFixedLength();

                    b.HasKey("Pk");

                    b.ToTable("Tabella1");
                });
#pragma warning restore 612, 618
        }
    }
}
